# filename: ex109.rq

PREFIX dm:  <http://learningsparql.com/ns/demo#>
PREFIX db: <http://dbpedia.org/resource/>

SELECT ?s ?cost ?location
WHERE
{
  ?s dm:location ?location ;
     dm:cost ?cost . 
  FILTER (?location IN (db:Montreal, db:Lisbon)) . 
}

-------------------------------------------------------------------
| s
| cost | location
|
====================================================================
| <http://learningsparql.com/ns/data#item857> | 12| db:Montreal |
| <http://learningsparql.com/ns/data#item126> | 5| db:Lisbon|
--------------------------------------------------------------------
