# filename: ex061.rq

PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

SELECT ?first ?last ?workTel ?nick
WHERE
{
  ?s ab:firstName ?first ;
     ab:lastName ?last .
  OPTIONAL
  { ?s ab:workTel ?workTel . }
  OPTIONAL
  { ?s ab:nick ?nick .  }

}

------------------------------------------------------
| first | last | workTel | nick  |
======================================================
| "Craig" | "Ellis" | "(245) 315-5486" |    |
| "Cindy"| "Marshall" |                |     |
| "Richard" | "Mutt"  |                | "Dick" |
------------------------------------------------------